import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'

export type Locale = 'ja' | 'en'
type Vars = Record<string, string | number>

const ja: Record<string, string> = {
  'language.label': '言語', 'language.ja': '日本語', 'language.en': 'English',
  'common.loading': '読み込み中…', 'common.search': '検索', 'common.previous': '前へ', 'common.next': '次へ', 'common.working': '処理中…', 'common.unrated': '未評価', 'common.unknown': '不明', 'common.optional': '任意', 'common.current': '現在',
  'auth.staff': '運営用', 'auth.title': 'Enhanced Level Forum 管理画面', 'auth.email': 'メールアドレス', 'auth.password': 'パスワード', 'auth.login': 'ログイン', 'auth.logout': 'ログアウト', 'auth.loginFailed': 'ログインに失敗しました', 'auth.denied': 'アクセスできません', 'auth.deniedDetail': '{role} には管理画面へのアクセス権がありません。',
  'tab.overview': '概要', 'tab.levels': '譜面', 'tab.references': '基準譜面', 'tab.proposals': '提案', 'tab.users': 'ユーザー', 'tab.imports': 'データ取り込み', 'tab.audit': '操作履歴',
  'head.management': '管理',
  'overview.title': '概要', 'overview.levels': '譜面数', 'overview.review': '要確認の基準譜面', 'overview.proposals': '審議中の提案', 'overview.users': 'ユーザー数', 'overview.ruleTitle': '運用ルール', 'overview.rule': '基準譜面になっている譜面も難易度変更を妨げません。確定難易度と基準譜面の位置が一致しなくなった場合は、その基準譜面を「要確認」にします。',
  'levels.title': '譜面', 'levels.create': '譜面を新規登録', 'levels.existing': '登録済み', 'levels.select': '編集する譜面を選択してください。', 'levels.saved': '保存しました', 'levels.song': '楽曲名 / 作曲者', 'levels.levelTitle': '譜面名', 'levels.creator': '譜面制作者', 'levels.versionLabel': '版の名前', 'levels.shaOptional': 'SHA-256（任意）', 'levels.downloadOptional': '配布URL（任意）', 'levels.createButton': '登録',
  'level.publishRerate': '確定難易度を変更', 'level.ratingRule': '確定難易度は P/G/U の整数段階のみです。小数値や5段階の傾きは判断材料として別に扱います。', 'level.confidence': '確信度 0..1', 'level.reason': '変更理由', 'level.publish': '難易度を確定', 'level.addVersion': '新しい版を追加', 'level.versionExample': '版の名前（例: Nerfed）', 'level.sha': 'SHA-256', 'level.download': '配布URL', 'level.addCurrent': '追加して現行版にする', 'level.versions': '版一覧', 'level.noSha': 'SHAなし',
  'references.title': '基準譜面', 'references.add': '基準譜面を追加', 'references.level': '譜面', 'references.technique': '技法', 'references.noPosition': '位置指定なし', 'references.lower': '低め', 'references.slightlyLower': 'やや低め', 'references.center': '中央', 'references.slightlyHigher': 'やや高め', 'references.higher': '高め', 'references.confidence': '確信度', 'references.addButton': '基準譜面に追加', 'references.slot': '位置', 'references.status': '状態', 'references.action': '操作', 'references.review': '要確認にする', 'references.retire': '廃止',
  'proposals.title': '提案', 'proposals.approveRerate': '承認して難易度変更を適用', 'proposals.approveReference': '承認して基準譜面の変更を適用', 'proposals.approve': '承認', 'proposals.reject': '却下', 'proposals.applying': '適用中…', 'proposals.agree': '賛成', 'proposals.disagree': '反対', 'proposals.abstain': '保留', 'proposals.decisionFailed': '提案の処理に失敗しました', 'proposals.appliedRerate': '{rating} を適用し、基準譜面 {count} 件を要確認にしました。', 'proposals.appliedReference': '{type} を基準譜面 {id} に適用しました。', 'proposals.approvedReason': '管理画面で承認', 'proposals.rejectedReason': '管理画面で却下',
  'users.title': 'ユーザー', 'users.adminOnly': '管理者のみ操作できます。', 'users.create': 'ユーザーを作成', 'users.email': 'メールアドレス', 'users.name': '表示名', 'users.role': '権限', 'users.change': '変更', 'users.displayName': '表示名', 'users.password': 'パスワード（12文字以上）', 'users.createButton': '作成', 'users.active': '有効', 'users.disabled': '無効', 'users.disable': '無効化', 'users.activate': '有効化', 'users.resetPassword': 'パスワードを再設定', 'users.newPassword': '新しいパスワード', 'users.changeRole': '権限を変更',
  'imports.title': 'データ取り込み', 'imports.runTuf': 'TUFを今すぐ取り込む', 'imports.running': '取り込み中…', 'imports.snapshot': '取得データ', 'imports.imported': '取り込みました', 'imports.failed': '取り込みに失敗しました', 'imports.noSnapshot': 'まだTUFデータを取り込んでいません。', 'imports.storeRaw': '外部データを手動保存', 'imports.rawHelp': 'ここで保存する外部データは判断材料として保持され、確定難易度を直接変更しません。', 'imports.sourceVersion': '取得元の版 / 時刻', 'imports.invalidJson': 'JSONの形式が正しくありません', 'imports.store': '保存', 'imports.source': '取得元', 'imports.version': '版', 'imports.importedAt': '取り込み日時',
  'audit.title': '操作履歴', 'audit.action': '操作', 'audit.actor': '実行者', 'audit.target': '対象', 'audit.time': '日時', 'audit.details': '詳細',
  'tuf.queueEyebrow': 'TUF → ELF', 'tuf.queueTitle': 'TUF未照合データ', 'tuf.unlinkedCount': '未照合 {count} 件', 'tuf.queueDescription': '最新のTUF取得データから、まだELFの譜面と結び付いていないものを表示します。既存譜面との照合・新規譜面の登録のどちらでも、TUFの難易度を確定難易度へ直接コピーしません。', 'tuf.snapshot': '取得データ', 'tuf.searchPlaceholder': 'TUF ID / 譜面名 / 楽曲名 / 制作者', 'tuf.noSnapshot': 'TUFデータはまだ取り込まれていません。', 'tuf.noUnlinked': '条件に一致する未照合データはありません。', 'tuf.referencesShort': '基準 {count} 件 ({types})', 'tuf.issuesShort': '問題 E{error}/W{warning}', 'tuf.creatorUnknown': '制作者不明', 'tuf.shaNotSupplied': 'TUF側にSHAなし', 'tuf.downloadPresent': '取り込んだ情報に配布URLがあります。', 'tuf.findExisting': '既存のELF譜面を探す', 'tuf.find': '探す', 'tuf.selectLevel': 'ELF譜面を選択', 'tuf.versionLink': '版の照合（任意）', 'tuf.levelOnly': '譜面だけを照合', 'tuf.versionCurrent': '現行版', 'tuf.versionNoSha': 'SHAなし', 'tuf.versionLinkHelp': '譜面IDの対応は今後の取り込みでも使われます。この取得データだけ特定の版を明示的に結び付けることもできますが、次回以降に版まで自動照合するにはSHA-256の完全一致が必要です。', 'tuf.shaConflict': '選択した版のSHA-256がTUF側と異なります。この組み合わせはAPIで拒否されます。', 'tuf.link': 'TUF IDをELF譜面と照合', 'tuf.linked': 'TUF #{id} → {title}{version} を照合しました。', 'tuf.linkFailed': '照合に失敗しました', 'tuf.createNew': '新しいELF譜面として登録', 'tuf.createHelp': '取り込んだ情報は入力の初期値にすぎません。必要なら修正してから登録してください。登録後すぐにこのTUF IDと照合されますが、確定難易度は未評価のままです。', 'tuf.createSong': '楽曲名 / 作曲者', 'tuf.createTitle': '譜面名', 'tuf.createCreator': '譜面制作者', 'tuf.createVersion': '版の名前', 'tuf.createSha': 'SHA-256（任意）', 'tuf.createUrl': '配布URL（任意）', 'tuf.createButton': '新しい譜面として登録して照合', 'tuf.created': 'TUF #{id} → {title} / {version} を新規登録して照合しました。確定難易度は未評価のままです。', 'tuf.createFailed': '譜面の新規登録に失敗しました', 'tuf.createPermission': '新しいELF譜面の登録にはモデレーターまたは管理者権限が必要です。基準譜面管理者は既存譜面との照合だけ行えます。', 'tuf.selectUnlinked': '未照合のTUFデータを選択してください。',
  'evidence.eyebrow': 'TUFの難易度情報', 'evidence.title': '照合済みの難易度情報', 'evidence.linkedCount': '照合済み {count} 件', 'evidence.description': '最新のTUF難易度とELFの確定難易度を比較します。ここから作成するのは難易度変更の提案だけで、確定難易度を直接変更することはありません。', 'evidence.searchPlaceholder': 'TUF ID / TUF譜面名 / ELF譜面名 / 制作者', 'evidence.actionableOnly': '難易度変更を提案できる差分だけ表示', 'evidence.noMatch': '条件に一致する照合済みデータはありません。', 'evidence.changedFrom': 'TUF変更: {from} から', 'evidence.latest': 'TUF 最新', 'evidence.canonical': 'ELF 確定難易度', 'evidence.targetVersion': '対象の版', 'evidence.explicitLink': 'TUFと明示的に照合した版', 'evidence.currentVersion': '現在のELF版', 'evidence.shaNotStored': 'SHA未登録', 'evidence.noTargetVersion': 'このELF譜面には対象にできる版がありません。', 'evidence.previousChanged': '前回のTUF: {from} → {to}（変更あり）', 'evidence.previousUnchanged': '前回のTUF: {from} → {to}（変更なし）', 'evidence.noPrevious': 'このTUF IDには以前の難易度情報がありません。', 'evidence.referenceEvidence': 'TUFの基準譜面情報', 'evidence.noReference': 'この取得データにはTUFの基準譜面情報がありません。', 'evidence.importIssues': '取り込み時の問題: E{error} / W{warning} / I{info}', 'evidence.matches': 'ELFの確定難易度はすでにこのTUF P/G/U難易度と一致しています。変更提案は不要です。', 'evidence.openProposal': '同じ変更先を扱う審議中の提案があります: {id}', 'evidence.specialOnly': 'P/G/U以外のTUF難易度は判断材料として保存しますが、ELFの確定難易度変更へは直接変換できません。', 'evidence.reasonPlaceholder': '追加の確認事項（任意）。元のTUF情報は自動で提案に添付されます。', 'evidence.createProposal': 'このTUF情報から難易度変更を提案', 'evidence.creating': '作成中…', 'evidence.created': '提案 {id} を作成しました: {title}', 'evidence.createFailed': '提案の作成に失敗しました', 'evidence.select': '照合済みのTUF情報を選択してください。',
  'status.ACTIVE': '有効', 'status.NEEDS_REVIEW': '要確認', 'status.RETIRED': '廃止', 'status.OPEN': '審議中', 'status.APPROVED': '承認', 'status.REJECTED': '却下', 'status.WITHDRAWN': '取り下げ',
  'proposalType.RERATE': '難易度変更', 'proposalType.REFERENCE_ADD': '基準譜面を追加', 'proposalType.REFERENCE_MOVE': '基準譜面を移動', 'proposalType.REFERENCE_REMOVE': '基準譜面を削除', 'proposalType.METADATA': '情報修正', 'proposalType.OTHER': 'その他',
  'role.VIEWER': '閲覧者', 'role.RATER': '評価者', 'role.REFERENCE_MANAGER': '基準譜面管理者', 'role.MODERATOR': 'モデレーター', 'role.ADMIN': '管理者',
}

const en: Record<string, string> = {
  ...ja,
  'language.label':'Language','language.ja':'日本語','language.en':'English','common.loading':'Loading…','common.search':'Search','common.previous':'Previous','common.next':'Next','common.working':'Working…','common.unrated':'Unrated','common.unknown':'Unknown','common.optional':'Optional','common.current':'current',
  'auth.staff':'Staff','auth.title':'Enhanced Level Forum Admin','auth.email':'Email','auth.password':'Password','auth.login':'Login','auth.logout':'Logout','auth.loginFailed':'Login failed','auth.denied':'Access denied','auth.deniedDetail':'{role} does not have staff access.',
  'tab.overview':'Overview','tab.levels':'Levels','tab.references':'References','tab.proposals':'Proposals','tab.users':'Users','tab.imports':'Imports','tab.audit':'Audit log','head.management':'Management',
  'overview.title':'Overview','overview.levels':'Levels','overview.review':'References needing review','overview.proposals':'Open proposals','overview.users':'Users','overview.ruleTitle':'Operational rule','overview.rule':'Do not block rerating a Reference chart. If its canonical rating moves away from the Reference slot, mark that Reference as Needs review.',
  'levels.title':'Levels','levels.create':'Create level','levels.existing':'Existing','levels.select':'Select a level.','levels.saved':'Saved','levels.song':'Song / composer','levels.levelTitle':'Level title','levels.creator':'Creator','levels.versionLabel':'Version label','levels.shaOptional':'SHA-256 (optional)','levels.downloadOptional':'Download URL (optional)','levels.createButton':'Create',
  'level.publishRerate':'Publish canonical rerate','level.ratingRule':'Canonical difficulty uses integer P/G/U tiers only. Decimal values and five-step lean remain separate evidence.','level.confidence':'confidence 0..1','level.reason':'Decision reason','level.publish':'Publish rerate','level.addVersion':'Add version','level.versionExample':'Label e.g. Nerfed','level.sha':'SHA-256','level.download':'Download URL','level.addCurrent':'Add & make current','level.versions':'Versions','level.noSha':'no sha',
  'references.title':'References','references.add':'Add Reference','references.level':'Level','references.technique':'Technique','references.noPosition':'No position hint','references.lower':'lower side','references.slightlyLower':'slightly lower','references.center':'center','references.slightlyHigher':'slightly higher','references.higher':'higher side','references.confidence':'confidence','references.addButton':'Add Reference','references.slot':'Slot','references.status':'Status','references.action':'Action','references.review':'Review','references.retire':'Retire',
  'proposals.title':'Proposals','proposals.approveRerate':'Approve & apply rerate','proposals.approveReference':'Approve & apply Reference','proposals.approve':'Approve','proposals.reject':'Reject','proposals.applying':'Applying…','proposals.agree':'Agree','proposals.disagree':'Disagree','proposals.abstain':'Abstain','proposals.decisionFailed':'Proposal decision failed','proposals.appliedRerate':'Applied rerate {rating}; {count} Reference(s) moved to NEEDS_REVIEW.','proposals.appliedReference':'Applied {type} to Reference {id}.','proposals.approvedReason':'Approved in admin panel','proposals.rejectedReason':'Rejected in admin panel',
  'users.title':'Users','users.adminOnly':'ADMIN only.','users.create':'Create user','users.email':'Email','users.name':'Name','users.role':'Role','users.change':'Change','users.displayName':'Display name','users.password':'Password (12+ chars)','users.createButton':'Create','users.active':'Active','users.disabled':'Disabled','users.disable':'Disable','users.activate':'Activate','users.resetPassword':'Reset password','users.newPassword':'New password','users.changeRole':'Change role',
  'imports.title':'Imports','imports.runTuf':'Run TUF import now','imports.running':'Importing…','imports.snapshot':'Snapshot','imports.imported':'Imported','imports.failed':'Import failed','imports.noSnapshot':'No TUF snapshot has been imported yet.','imports.storeRaw':'Store raw snapshot','imports.rawHelp':'Imported observations are stored as evidence and never change canonical rating directly.','imports.sourceVersion':'source version / timestamp','imports.invalidJson':'Invalid JSON','imports.store':'Store','imports.source':'Source','imports.version':'Version','imports.importedAt':'Imported at',
  'audit.title':'Audit log','audit.action':'Action','audit.actor':'Actor','audit.target':'Entity','audit.time':'Time','audit.details':'Details',
  'tuf.queueTitle':'Reconciliation queue','tuf.unlinkedCount':'{count} unlinked','tuf.queueDescription':'Shows only unlinked levels from the latest TUF snapshot. Linking an existing Level or creating a new one never copies TUF rating directly into canonical rating.','tuf.snapshot':'Snapshot','tuf.searchPlaceholder':'TUF ID / title / song / creator','tuf.noSnapshot':'No TUF snapshot has been imported yet.','tuf.noUnlinked':'No unlinked rows match this search.','tuf.referencesShort':'refs {count} ({types})','tuf.issuesShort':'issues E{error}/W{warning}','tuf.creatorUnknown':'creator unknown','tuf.shaNotSupplied':'not supplied by TUF','tuf.downloadPresent':'Download URL is present in the imported evidence.','tuf.findExisting':'Find existing ELF Level','tuf.find':'Find','tuf.selectLevel':'Select ELF Level','tuf.versionLink':'Version link (optional)','tuf.levelOnly':'Level only','tuf.versionCurrent':'current','tuf.versionNoSha':'no SHA','tuf.versionLinkHelp':'Level-only mapping is persistent for future imports. A Version is attached explicitly only to this snapshot; future imports still require an exact SHA match for automatic Version linkage.','tuf.shaConflict':'Selected Version has a different SHA-256. The API will reject this link.','tuf.link':'Link TUF ID to ELF','tuf.linked':'Linked TUF #{id} → {title}{version}','tuf.linkFailed':'Link failed','tuf.createNew':'Create new ELF Level','tuf.createHelp':'Imported metadata is only a starting point. Edit it before creation if needed. The new Level is immediately reconciled to this TUF ID, but stays canonically Unrated.','tuf.createSong':'Song / composer','tuf.createTitle':'Level title','tuf.createCreator':'Creator','tuf.createVersion':'Version label','tuf.createSha':'SHA-256 (optional)','tuf.createUrl':'Download URL (optional)','tuf.createButton':'Create ELF Level & link','tuf.created':'Created & linked TUF #{id} → {title} / {version}. ELF canonical remains Unrated.','tuf.createFailed':'Create Level failed','tuf.createPermission':'Creating a new canonical ELF Level requires MODERATOR or ADMIN. REFERENCE_MANAGER can still link this TUF ID to an existing Level.','tuf.selectUnlinked':'Select an unlinked TUF row.',
  'evidence.eyebrow':'TUF evidence','evidence.title':'Linked rating evidence','evidence.linkedCount':'{count} linked','evidence.description':'Compares the latest TUF snapshot with ELF canonical rating. This creates RERATE proposals only and never changes canonical rating directly.','evidence.searchPlaceholder':'TUF ID / TUF title / ELF title / creator','evidence.actionableOnly':'Show only rating differences that can create a proposal','evidence.noMatch':'No linked TUF evidence matches this filter.','evidence.changedFrom':'TUF changed from {from}','evidence.latest':'TUF latest','evidence.canonical':'ELF canonical','evidence.targetVersion':'Target version','evidence.explicitLink':'explicit TUF version link','evidence.currentVersion':'current ELF version','evidence.shaNotStored':'not stored','evidence.noTargetVersion':'This ELF level has no target version.','evidence.previousChanged':'Previous TUF snapshot: {from} → {to} (changed)','evidence.previousUnchanged':'Previous TUF snapshot: {from} → {to} (unchanged)','evidence.noPrevious':'No previous TUF rating observation is stored for this ID.','evidence.referenceEvidence':'TUF Reference evidence','evidence.noReference':'No TUF Reference entry in this snapshot.','evidence.importIssues':'Import issues: E{error} / W{warning} / I{info}','evidence.matches':'ELF already matches this TUF P/G/U rating. No rerate proposal is needed.','evidence.openProposal':'An open proposal already covers this target: {id}','evidence.specialOnly':'Special/non-PGU TUF labels are evidence only and cannot be converted into an ELF canonical RERATE proposal.','evidence.reasonPlaceholder':'Additional review context (optional). Source evidence is added automatically.','evidence.createProposal':'Create RERATE proposal from TUF evidence','evidence.creating':'Creating…','evidence.created':'Created proposal {id}: {title}','evidence.createFailed':'Proposal creation failed','evidence.select':'Select linked TUF evidence to compare it with ELF.',
  'status.ACTIVE':'Active','status.NEEDS_REVIEW':'Needs review','status.RETIRED':'Retired','status.OPEN':'Open','status.APPROVED':'Approved','status.REJECTED':'Rejected','status.WITHDRAWN':'Withdrawn',
  'proposalType.RERATE':'Rerate','proposalType.REFERENCE_ADD':'Add Reference','proposalType.REFERENCE_MOVE':'Move Reference','proposalType.REFERENCE_REMOVE':'Remove Reference','proposalType.METADATA':'Metadata','proposalType.OTHER':'Other',
  'role.VIEWER':'Viewer','role.RATER':'Rater','role.REFERENCE_MANAGER':'Reference Manager','role.MODERATOR':'Moderator','role.ADMIN':'Admin',
}

function detectLocale(): Locale { const stored=localStorage.getItem('elf_locale'); if(stored==='ja'||stored==='en')return stored; return navigator.language.toLowerCase().startsWith('ja')?'ja':'en' }
function interpolate(template:string,vars?:Vars){if(!vars)return template;return template.replace(/\{(\w+)\}/g,(_,key:string)=>String(vars[key]??`{${key}}`))}

type Value={locale:Locale;setLocale:(locale:Locale)=>void;t:(key:string,vars?:Vars)=>string;date:(value:string|Date)=>string;status:(value:string)=>string;proposalType:(value:string)=>string;role:(value:string)=>string}
const Context=createContext<Value|null>(null)
export function I18nProvider({children}:{children:React.ReactNode}){const[locale,setLocaleState]=useState<Locale>(detectLocale);useEffect(()=>{document.documentElement.lang=locale},[locale]);const setLocale=(next:Locale)=>{localStorage.setItem('elf_locale',next);setLocaleState(next)};const value=useMemo<Value>(()=>{const dict=locale==='ja'?ja:en;const t=(key:string,vars?:Vars)=>interpolate(dict[key]??en[key]??key,vars);return{locale,setLocale,t,date:(value)=>new Intl.DateTimeFormat(locale==='ja'?'ja-JP':'en-US',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)),status:(value)=>t(`status.${value}`),proposalType:(value)=>t(`proposalType.${value}`),role:(value)=>t(`role.${value}`)}},[locale]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useI18n(){const value=useContext(Context);if(!value)throw new Error('useI18n must be used inside I18nProvider');return value}
export function LanguageSwitch(){const{locale,setLocale,t}=useI18n();return <select className="locale-switch" aria-label={t('language.label')} value={locale} onChange={(e)=>setLocale(e.target.value as Locale)}><option value="ja">{t('language.ja')}</option><option value="en">{t('language.en')}</option></select>}
