import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import type { LevelDetail, LevelListItem, ProposalRow, ReferenceRow, SessionUser, UserRole } from '@adoforum/shared'
import { api } from './api'
import './styles.css'

type Tab = 'overview' | 'levels' | 'references' | 'proposals' | 'users' | 'imports' | 'audit'

function App() {
  const [user, setUser] = useState<SessionUser | null>(null)
  const [loaded, setLoaded] = useState(false)
  const [tab, setTab] = useState<Tab>('overview')
  useEffect(() => { void api<{user:SessionUser|null}>('/auth/me').then((x)=>setUser(x.user)).finally(()=>setLoaded(true)) }, [])
  if (!loaded) return <div className="center">Loading…</div>
  if (!user) return <Login onLogin={setUser} />
  if (!['REFERENCE_MANAGER','MODERATOR','ADMIN'].includes(user.role)) return <div className="center"><div className="panel"><h1>Access denied</h1><p>{user.role} does not have staff access.</p></div></div>
  const staffTabs: Tab[] = user.role === 'ADMIN'
    ? ['overview','levels','references','proposals','users','imports','audit']
    : user.role === 'MODERATOR'
      ? ['overview','levels','references','proposals','imports','audit']
      : ['overview','references','imports']
  return <div className="admin-shell">
    <aside><div className="brand">AdoForum <span>Admin</span></div><p className="who">{user.displayName}<small>{user.role}</small></p>{staffTabs.map((x)=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}<button className="logout" onClick={async()=>{await api('/auth/logout',{method:'POST'});setUser(null)}}>Logout</button></aside>
    <main>{tab==='overview'&&<Overview/>}{tab==='levels'&&<Levels user={user}/>} {tab==='references'&&<References/>}{tab==='proposals'&&<Proposals/>}{tab==='users'&&<Users user={user}/>} {tab==='imports'&&<Imports/>}{tab==='audit'&&<Audit/>}</main>
  </div>
}

function Login({onLogin}:{onLogin:(u:SessionUser)=>void}){
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState('')
  return <div className="center"><div className="panel login"><p className="eyebrow">Staff</p><h1>AdoForum Admin</h1><label>Email<input value={email} onChange={(e)=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={(e)=>setPassword(e.target.value)}/></label>{error&&<p className="error">{error}</p>}<button onClick={async()=>{try{const x=await api<{user:SessionUser}>('/auth/login',{method:'POST',body:JSON.stringify({email,password})});onLogin(x.user)}catch(e){setError(e instanceof Error?e.message:'Login failed')}}}>Login</button></div></div>
}

function Overview(){const [data,setData]=useState<any>(null);useEffect(()=>{void api('/admin/overview').then(setData)},[]);return <><Head title="Overview"/><div className="stats">{[['Levels',data?.levels],['References needing review',data?.references_needing_review],['Open proposals',data?.open_proposals],['Users',data?.users]].map(([k,v])=><div className="stat" key={String(k)}><span>{k}</span><strong>{v??'—'}</strong></div>)}</div><div className="panel"><h2>Operational rule</h2><p>Reference chartのrerateを止めない。canonical ratingがReference slotから外れた場合はReferenceを自動で <code>NEEDS_REVIEW</code> にする。</p></div></>}

function Head({title,children}:{title:string;children?:React.ReactNode}){return <div className="head"><div><p className="eyebrow">Management</p><h1>{title}</h1></div>{children}</div>}

function Levels({user}:{user:SessionUser}){
  const [levels,setLevels]=useState<LevelListItem[]>([]); const [selected,setSelected]=useState<LevelDetail|null>(null); const [msg,setMsg]=useState('')
  const load=()=>api<{levels:LevelListItem[]}>('/levels?limit=100').then((x)=>setLevels(x.levels)); useEffect(()=>{void load()},[])
  const choose=async(id:string)=>setSelected(await api<LevelDetail>(`/levels/${id}`))
  return <><Head title="Levels"/><div className="split"><div className="panel"><h2>Create level</h2><CreateLevel onCreated={()=>void load()}/><h2>Existing</h2><div className="list">{levels.map((l)=><button className={selected?.id===l.id?'selected':''} key={l.id} onClick={()=>void choose(l.id)}><span>{l.currentRating?`${l.currentRating.family}${l.currentRating.tier}`:'—'}</span><strong>{l.title}</strong><small>{l.creator}</small></button>)}</div></div><div>{selected?<LevelEditor level={selected} onChanged={async()=>{setMsg('Saved');await choose(selected.id);await load()}}/>:<div className="panel"><p>Select a level.</p></div>}{msg&&<p className="notice">{msg}</p>}</div></div></>
}

function CreateLevel({onCreated}:{onCreated:()=>void}){
  const [song,setSong]=useState('');const [title,setTitle]=useState('');const [creator,setCreator]=useState('');const [label,setLabel]=useState('Original');const [sha,setSha]=useState('');const [url,setUrl]=useState('')
  return <div className="form"><input placeholder="Song / composer" value={song} onChange={(e)=>setSong(e.target.value)}/><input placeholder="Level title" value={title} onChange={(e)=>setTitle(e.target.value)}/><input placeholder="Creator" value={creator} onChange={(e)=>setCreator(e.target.value)}/><div className="grid"><input placeholder="Version label" value={label} onChange={(e)=>setLabel(e.target.value)}/><input placeholder="SHA-256 (optional)" value={sha} onChange={(e)=>setSha(e.target.value)}/></div><input placeholder="Download URL (optional)" value={url} onChange={(e)=>setUrl(e.target.value)}/><button disabled={!song||!title||!creator||!label} onClick={async()=>{await api('/admin/levels',{method:'POST',body:JSON.stringify({song,title,creator,version:{label,sha256:sha||null,downloadUrl:url||null}})});setSong('');setTitle('');setCreator('');setSha('');setUrl('');onCreated()}}>Create</button></div>
}

function LevelEditor({level,onChanged}:{level:LevelDetail;onChanged:()=>void}){
  const currentVersion=level.versions.find((v)=>v.id===level.currentVersionId)??level.versions[0]
  const [family,setFamily]=useState(level.currentRating?.family??'G');const [tier,setTier]=useState(level.currentRating?.tier??1);const [confidence,setConfidence]=useState(level.currentRating?.confidence??'');const [reason,setReason]=useState('')
  const [versionLabel,setVersionLabel]=useState('');const [versionSha,setVersionSha]=useState('');const [versionUrl,setVersionUrl]=useState('')
  return <div className="panel"><div className="title-row"><div><p className="eyebrow">{level.song}</p><h2>{level.title}</h2><p>{level.creator}</p></div><b className="big-rating">{level.currentRating?`${level.currentRating.family}${level.currentRating.tier}`:'Unrated'}</b></div><h3>Publish canonical rerate</h3><p className="muted">正式difficultyは整数tierのみ。小数値や5区分はcanonicalにしません。</p><div className="grid three"><select value={family} onChange={(e)=>setFamily(e.target.value as any)}><option>P</option><option>G</option><option>U</option></select><input type="number" min="1" max="30" value={tier} onChange={(e)=>setTier(Number(e.target.value))}/><input type="number" min="0" max="1" step=".05" placeholder="confidence 0..1" value={confidence} onChange={(e)=>setConfidence(e.target.value)}/></div><textarea placeholder="Decision reason" value={reason} onChange={(e)=>setReason(e.target.value)}/><button disabled={!currentVersion} onClick={async()=>{await api(`/admin/levels/${level.id}/ratings`,{method:'POST',body:JSON.stringify({levelVersionId:currentVersion?.id,family,tier,confidence:confidence===''?null:Number(confidence),reason})});setReason('');onChanged()}}>Publish rerate</button><h3>Add version</h3><div className="grid"><input placeholder="Label e.g. Nerfed" value={versionLabel} onChange={(e)=>setVersionLabel(e.target.value)}/><input placeholder="SHA-256" value={versionSha} onChange={(e)=>setVersionSha(e.target.value)}/></div><input placeholder="Download URL" value={versionUrl} onChange={(e)=>setVersionUrl(e.target.value)}/><button className="secondary" disabled={!versionLabel} onClick={async()=>{await api(`/admin/levels/${level.id}/versions`,{method:'POST',body:JSON.stringify({label:versionLabel,sha256:versionSha||null,downloadUrl:versionUrl||null,makeCurrent:true})});setVersionLabel('');setVersionSha('');setVersionUrl('');onChanged()}}>Add & make current</button><h3>Versions</h3>{level.versions.map((v)=><div className="row" key={v.id}><strong>{v.label}</strong>{v.id===level.currentVersionId&&<span className="pill">current</span>}<code>{v.sha256??'no sha'}</code></div>)}</div>
}

function References(){
  const [refs,setRefs]=useState<ReferenceRow[]>([]);const [levels,setLevels]=useState<LevelListItem[]>([]);const [levelId,setLevelId]=useState('');const [detail,setDetail]=useState<LevelDetail|null>(null);const [family,setFamily]=useState('G');const [tier,setTier]=useState(1);const [tech,setTech]=useState('TECH');const [hint,setHint]=useState('');const [conf,setConf]=useState('')
  const load=()=>api<{references:ReferenceRow[]}>('/references').then((x)=>setRefs(x.references));useEffect(()=>{void load();void api<{levels:LevelListItem[]}>('/levels?limit=100').then((x)=>setLevels(x.levels))},[]);useEffect(()=>{if(levelId)void api<LevelDetail>(`/levels/${levelId}`).then(setDetail);else setDetail(null)},[levelId])
  return <><Head title="References"/><div className="panel"><h2>Add reference</h2><div className="grid three"><select value={levelId} onChange={(e)=>setLevelId(e.target.value)}><option value="">Level</option>{levels.map((l)=><option key={l.id} value={l.id}>{l.title}</option>)}</select><select value={family} onChange={(e)=>setFamily(e.target.value)}><option>P</option><option>G</option><option>U</option></select><input type="number" min="1" max="30" value={tier} onChange={(e)=>setTier(Number(e.target.value))}/><input value={tech} onChange={(e)=>setTech(e.target.value)} placeholder="Technique"/><select value={hint} onChange={(e)=>setHint(e.target.value)}><option value="">No position hint</option><option value="-2">lower side</option><option value="-1">slightly lower</option><option value="0">center</option><option value="1">slightly higher</option><option value="2">higher side</option></select><input type="number" min="0" max="1" step=".05" value={conf} onChange={(e)=>setConf(e.target.value)} placeholder="confidence"/></div><button disabled={!detail?.currentVersionId||!tech} onClick={async()=>{await api('/admin/references',{method:'POST',body:JSON.stringify({levelVersionId:detail?.currentVersionId,family,tier,technique:tech,positionHint:hint===''?null:Number(hint),confidence:conf===''?null:Number(conf)})});void load()}}>Add reference</button></div><div className="table"><div className="tr th"><span>Slot</span><span>Level</span><span>Technique</span><span>Status</span><span>Action</span></div>{refs.map((r)=><div className="tr" key={r.id}><span>{r.family}{r.tier}</span><span>{r.levelTitle}</span><span>{r.technique}</span><span>{r.status}</span><span>{r.status!=='RETIRED'&&<><button className="tiny" onClick={async()=>{await api(`/admin/references/${r.id}`,{method:'PATCH',body:JSON.stringify({status:'NEEDS_REVIEW'})});void load()}}>Review</button><button className="tiny danger" onClick={async()=>{await api(`/admin/references/${r.id}`,{method:'PATCH',body:JSON.stringify({status:'RETIRED'})});void load()}}>Retire</button></>}</span></div>)}</div></>
}

function Proposals(){const [rows,setRows]=useState<ProposalRow[]>([]);const load=()=>api<{proposals:ProposalRow[]}>('/proposals').then((x)=>setRows(x.proposals));useEffect(()=>{void load()},[]);return <><Head title="Proposals"/><div className="cards">{rows.map((p)=><div className="panel" key={p.id}><div className="title-row"><div><span className="pill">{p.type}</span><h2>{p.title}</h2><p>{p.levelTitle} · {p.proposerName}</p></div><strong>{p.status}</strong></div><p>{p.reason}</p><p className="muted">Agree {p.agree} / Disagree {p.disagree} / Abstain {p.abstain}</p>{p.status==='OPEN'&&<div className="actions"><button onClick={async()=>{await api(`/admin/proposals/${p.id}/decision`,{method:'PATCH',body:JSON.stringify({status:'APPROVED',reason:'Approved in admin panel'})});void load()}}>Approve</button><button className="danger" onClick={async()=>{await api(`/admin/proposals/${p.id}/decision`,{method:'PATCH',body:JSON.stringify({status:'REJECTED',reason:'Rejected in admin panel'})});void load()}}>Reject</button></div>}</div>)}</div></>}

function Users({user}:{user:SessionUser}){const [rows,setRows]=useState<any[]>([]);const [email,setEmail]=useState('');const [name,setName]=useState('');const [password,setPassword]=useState('');const [role,setRole]=useState<UserRole>('VIEWER');const load=()=>api<{users:any[]}>('/admin/users').then((x)=>setRows(x.users));useEffect(()=>{if(user.role==='ADMIN')void load()},[user.role]);if(user.role!=='ADMIN')return <><Head title="Users"/><div className="panel">ADMIN only.</div></>;const roles:UserRole[]=['VIEWER','RATER','REFERENCE_MANAGER','MODERATOR','ADMIN'];return <><Head title="Users"/><div className="panel"><h2>Create user</h2><div className="grid"><input placeholder="email" value={email} onChange={(e)=>setEmail(e.target.value)}/><input placeholder="display name" value={name} onChange={(e)=>setName(e.target.value)}/><input type="password" placeholder="temporary password" value={password} onChange={(e)=>setPassword(e.target.value)}/><select value={role} onChange={(e)=>setRole(e.target.value as UserRole)}>{roles.map((r)=><option key={r}>{r}</option>)}</select></div><button disabled={!email||!name||!password} onClick={async()=>{await api('/admin/users',{method:'POST',body:JSON.stringify({email,displayName:name,password,role})});setEmail('');setName('');setPassword('');void load()}}>Create</button></div><div className="table"><div className="tr th"><span>Email</span><span>Name</span><span>Role</span><span>Change</span><span></span></div>{rows.map((u)=><div className="tr" key={u.id}><span>{u.email}</span><span>{u.display_name}</span><span>{u.role}</span><span><select defaultValue={u.role} onChange={async(e)=>{await api(`/admin/users/${u.id}/role`,{method:'PATCH',body:JSON.stringify({role:e.target.value})});void load()}}>{roles.map((r)=><option key={r}>{r}</option>)}</select></span><span/></div>)}</div></>}

function Imports(){const [rows,setRows]=useState<any[]>([]);const [source,setSource]=useState('TUF');const [version,setVersion]=useState('');const [raw,setRaw]=useState('{}');const [error,setError]=useState('');const load=()=>api<{snapshots:any[]}>('/admin/import-snapshots').then((x)=>setRows(x.snapshots));useEffect(()=>{void load()},[]);return <><Head title="Imports"/><div className="panel"><h2>Store raw snapshot</h2><p className="muted">Importはcanonical ratingを変更しません。外部観測値の正本としてそのまま保存します。</p><div className="grid"><input value={source} onChange={(e)=>setSource(e.target.value)}/><input placeholder="source version / timestamp" value={version} onChange={(e)=>setVersion(e.target.value)}/></div><textarea value={raw} onChange={(e)=>setRaw(e.target.value)}/>{error&&<p className="error">{error}</p>}<button onClick={async()=>{try{const parsed=JSON.parse(raw);await api('/admin/import-snapshots',{method:'POST',body:JSON.stringify({source,sourceVersion:version||null,rawData:parsed})});setError('');void load()}catch(e){setError(e instanceof Error?e.message:'Invalid JSON')}}}>Store</button></div><div className="table"><div className="tr th"><span>Source</span><span>Version</span><span>Imported at</span><span></span><span></span></div>{rows.map((r)=><div className="tr" key={r.id}><span>{r.source}</span><span>{r.source_version??'—'}</span><span>{new Date(r.imported_at).toLocaleString()}</span><span/><span/></div>)}</div></>}

function Audit(){const [rows,setRows]=useState<any[]>([]);useEffect(()=>{void api<{audit:any[]}>('/admin/audit').then((x)=>setRows(x.audit))},[]);return <><Head title="Audit log"/><div className="table"><div className="tr th"><span>Time</span><span>Actor</span><span>Action</span><span>Entity</span><span>Details</span></div>{rows.map((r)=><div className="tr" key={r.id}><span>{new Date(r.created_at).toLocaleString()}</span><span>{r.actor_name??'system'}</span><span>{r.action}</span><span>{r.entity_type}</span><code>{JSON.stringify(r.details)}</code></div>)}</div></>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
